# Javascript Node CircleCI 2.0 configuration file
version: 2

references:
  container_config: &container_config
    docker:
      - image: circleci/node:12
    working_directory: ~/react-components
  attach_workspace: &attach_workspace
    attach_workspace:
      at: ~/react-components

jobs:
  setup:
    <<: *container_config
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1.0-{{ .Branch }}-
            - yarn-packages-v1.0-
      - run: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: yarn-packages-v1.0-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ~/react-components
          paths:
            - node_modules

  end:
    <<: *container_config
    steps:
      - run: echo end

  lint:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run lint:es
      - run: npm run lint:style
  test:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run test -- -w=2 --collectCoverage --testPathIgnorePatterns=image.test.js
      - persist_to_workspace:
          root: ~/react-components
          paths:
            - coverage

  codecov:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: sudo npm install -g codecov
      - run: codecov

  build:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npm run build:dist
      - run: npm run build:lib
      - run: npm run build:ts
      # - run: npm run build:gh-pages
      - persist_to_workspace:
          root: ~/react-components
          paths:
            - dist
            - lib

  test lib:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run: npx jest tests/lib.manual.test.js

  deploy npm:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN_90" > ~/react-components/.npmrc
      - run:
          name: Publish package
          command: npm publish

  # deploy pages:
  #   <<: *container_config
  #   steps:
  #     - checkout
  #     - *attach_workspace
  #     - run:
  #         name: publish to github pages
  #         command: npm run deploy:gh-pages

workflows:
  version: 2
  test-and-build-and-deploy:
    jobs:
      - setup:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: gh-pages
      - lint:
          filters:
            tags:
              only: /^v.*/
          requires:
            - setup
      - test:
          filters:
            tags:
              only: /^v.*/
          requires:
            - lint
      - codecov:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
      - build:
          filters:
            tags:
              only: /^v.*/
          requires:
            - test
      - test lib:
          filters:
            tags:
              only: /^v.*/
          requires:
            - build
      - deploy npm:
          requires:
            - test lib
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      # - deploy pages:
      #     requires:
      #       - deploy npm
      #     filters:
      #       tags:
      #         only: /^v.*/
      #       branches:
      #         ignore: /.*/
      - end:
          filters:
            tags:
              only: /^v.*/
          requires:
            - lint
            - test
            - build
            - test lib
            - deploy npm
            # - deploy pages
